---
title: "Nonlinear effect of prediction error on recognition-based episodic memory updating"
date: "`r Sys.Date()`"
output:
  html_document:
    theme: cosmo 
    highlight: pygments
subtitle: Data & R script (in press, KJEP:CB)
mainfont: Noto Sans CJK KR
---

```{r, echo=FALSE, warning=FALSE, message=FALSE}
# install.packages("devtools")
pacman::p_load_gh("mitchelloharawild/icons")
```

<br><br>

## Authors

* Taehoon Kim (Department of Psychology, Yonsei University, taehoon.kim@yonsei.ac.kr) 
* Do-Joon Yi (Department of Psychology, Yonsei University, dojoon.yi@yonsei.ac.kr)

<br>

## Abstract

The reactivation of memories can transiently render them vulnerable to and updated with newly learned information. Recent evidence implicates prediction error as necessary to trigger such reconsolidation processes. However, it is unknown how the prediction error level relates to memory updating. Using a 3-day object learning paradigm, we tested the updating of memories as a function of prediction error during reactivation. On Day 1, participants learned the first list of objects divided into a few subsets. On Day 2, the experimental group was reminded of the first list and then learned the second list while the control group went through reverse order. Notably, when the memories of the first list were reactivated, different levels of prediction error occurred for the subsets. On Day 3, the experimental group was more likely to misattribute the source of objects from the second list as being from the first list, the extent of which was prominent with a moderate level of prediction error. No such pattern was observed for the control group. These results indicate that only a moderate prediction error is required for memory updating and that a new memory may be formed when there is too much prediction error. The current study suggests that prediction error is a necessary but not sufficient condition for memory updating.


***
[[View on Github `r icon_style(fontawesome("github-alt", style = "brands"), scale = 4, fill = "#56B4E9")`](https://github.com/cogneuro/MemUpdatingPE)]{style="float:right"}
